---
- name: Local Machine Setup
  hosts: localhost
  connection: local

  vars:
    PROJECT_DIR: "/root/kardanai"

  pre_tasks:
    - name: Wait for apt lock release
      shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do sleep 1; done
      
  tasks:
    - name: Install curl and python3-pip
      package:
        name: 
          - curl
          - python3-pip
          - python3-poetry
          - llvm
          - llvm-dev
          - python3-dev
          - build-essential
        state: present

    - name: Install Poetry
      shell: |
        export HOME=/root
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Run Poetry Install
      shell: "poetry install"
      args:
        chdir: "{{ PROJECT_DIR }}"
      environment:
        PATH: "/root/.local/bin:{{ ansible_env.PATH }}"
        HOME: "/root"

    - name: Install Ollama
      shell: curl -fsSL https://ollama.com/install.sh | sh
      args:
        creates: /usr/local/bin/ollama

    - name: Pull llama2
      shell: |
        export HOME=/root
        ollama pull llama2:latest
      
    - name: Run Ollama service
      shell: service ollama start
