---
- name: Local Machine Setup
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Wait for apt lock release
      shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do sleep 1; done
      
  tasks:
    - name: Install curl
      package:
        name: curl
        state: present

    - name: Install Ollama
      shell: curl -fsSL https://ollama.com/install.sh | sh
      args:
        creates: /usr/local/bin/ollama  # предотвращает повторную установку

    - name: Run Ollama service
      shell: service ollama start

    - name: Pull llama2
      shell: |
        export HOME=/root
        ollama pull llama3.2:1b
