ARG TARGETPLATFORM=linux/amd64
FROM nvidia/cuda:12.8.0-cudnn-runtime-ubuntu24.04
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:$PATH"
ENV POETRY_VIRTUALENVS_PATH=/root/.venv
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN apt update && \
    apt install build-essential htop tmux llvm-14 llvm-14-dev git python3 pipx nano openssh-server -y && \
    update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100 && \
    pipx ensurepath && \
    pipx install poetry && \
    apt-get clean && \
    poetry install --no-interaction && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/

# TODO add poetry cache
# docker buildx build --platform linux/amd64 --file=Dockerfile-base -t maxsolyaris/kardanai:base .