---
- name: Local Machine Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    PROJECT_DIR: "/app"
    DOCKER_IMAGE: "maxsolyaris/kardanai:latest"
  vars_files:
    - "/tmp/{{ PROJECT_DIR }}/data/config/ansible/vars.yml"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - nvidia-container-toolkit
        state: present

    - name: NVIDIA Container Toolkit Docker
      tasks:
        - name: nvidia-ctk
          command: nvidia-ctk runtime configure --runtime=docker

    - name: nvidia-ctk runtime status
      command: nvidia-ctk runtime status
      register: nvidia_status
    
    - name: nvidia_status
      debug:
        var: nvidia_status.stdout_lines

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install required packages python3-pip
      apt:
        name: 
          - python3-pip
          - python3-docker
        state: present

    - name: Log in to DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        
    - name: Pull private image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull
        force_source: yes

    - name: Run container
      docker_container:
        name: train
        image: "{{ DOCKER_IMAGE }}"
        volumes:
          - "{{ PROJECT_DIR }}:/app"
        state: started
        device_requests:
          - capabilities: [["gpu"]]  # Эквивалент --gpus all
        ipc_mode: host               # Эквивалент --ipc=host
        ulimits:
          - name: memlock
            soft: -1
            hard: -1
          - name: stack
            soft: 67108864
            hard: 67108864
