---
- name: Local Machine Setup
  hosts: localhost
  connection: local

  vars:
    PROJECT_DIR: "/root/kardanai"

  pre_tasks:
    - name: Wait for apt lock release
      shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do sleep 1; done
      
  tasks:
    - name: Install required packages
      package:
        name: 
          - curl
          - python3-pip
          - python3-dev
          - build-essential
          - python3-poetry
          - llvm-14
          - llvm-14-dev
          - git
        state: present

    - name: Set LLVM 14 as default
      shell: |
        update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100

    - name: Run Poetry Install
      shell: "poetry install"
      args:
        chdir: "{{ PROJECT_DIR }}"

    - name: Install Ollama
      shell: curl -fsSL https://ollama.com/install.sh | sh
      args:
        creates: /usr/local/bin/ollama

    - name: Run Ollama service
      shell: service ollama start

    - name: Pull llama2
      shell: |
        export HOME=/root
        ollama pull llama3.2:1b
      