---
- name: Local Machine Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    PROJECT_DIR: "/app"
    DOCKER_IMAGE: "maxsolyaris/kardanai:latest"
  vars_files:
    - "/tmp/{{ PROJECT_DIR }}/data/config/ansible/vars.yml"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Nvidia repository
      ansible.builtin.shell: |
        set -e
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \| sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
          && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \| \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \| \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        executable: /bin/bash
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: nvidia-container-toolkit
      apt:
        name:
          - nvidia-container-toolkit
        state: present
        update_cache: yes

    - name: NVIDIA Container Toolkit Docker
      command: nvidia-ctk runtime configure --runtime=docker

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Nvidia repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
        mode: '0644'
        content: |
          deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/ubuntu{{ ubuntu_codename.stdout }}/ {{ ubuntu_codename.stdout }} main

    - name: Install required packages python3-pip
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
          - python3-docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        
    - name: Pull private image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull
        force_source: yes

    - name: Run container
      docker_container:
        name: train
        image: "{{ DOCKER_IMAGE }}"
        volumes:
          - "{{ PROJECT_DIR }}:/app"
        state: started
        device_requests:
          - capabilities: [["gpu"]]  # Эквивалент --gpus all
        ipc_mode: host               # Эквивалент --ipc=host
        ulimits:
          - name: memlock
            soft: -1
            hard: -1
          - name: stack
            soft: 67108864
            hard: 67108864
