mac_config:
  name: "mac"
  num_train_epochs: 1
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 2
  eval_strategy: "steps"
  eval_steps: 70
  save_steps: 200
  learning_rate: 0.00001
  weight_decay: 0.01
  fp16: false
  use_cpu: true
  warmup_ratio: 0.1
  save_total_limit: 1
  do_train: true
  do_eval: true
  disable_tqdm: false
  logging_first_step: true
  logging_steps: 1
  overwrite_output_dir: true
  logging_dir: "data/model/logs"
  report_to: ["tensorboard", "neptune"]
  output_dir: "data/model/llama_lora_output"


h100_config:
  name: "h100"
  num_train_epochs: 3
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  eval_strategy: "steps"
  eval_steps: 100
  save_steps: 500
  learning_rate: 0.00002
  weight_decay: 0.01
  fp16: true
  use_cpu: false
  warmup_ratio: 0.1
  save_total_limit: 2
  do_train: true
  do_eval: true
  disable_tqdm: false
  logging_first_step: true
  logging_steps: 5
  overwrite_output_dir: true
  logging_dir: "data/model/logs"
  report_to: ["tensorboard", "neptune"]
  output_dir: "data/model/llama_lora_output"
